// <auto-generated />
using System;
using FlockWise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlockWise.Infrastructure.Migrations
{
    [DbContext(typeof(FlockWiseDbContext))]
    [Migration("20250916114615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlockWise.Core.Entities.BirthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BirthComplications")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("BottleFedLamb")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("DateOfBirthUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FatherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MotherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SheepId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightBornKgs")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.HasIndex("SheepId")
                        .IsUnique();

                    b.ToTable("BirthRecords", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<double>("Size")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Flock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EstablishedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("UserId");

                    b.ToTable("Flocks", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.FlockNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlockId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("FlockId");

                    b.ToTable("FlockNotes", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.LambingNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LambingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LambingRecordId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("LambingId");

                    b.HasIndex("LambingRecordId");

                    b.ToTable("LambingNotes", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.LambingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssistanceType")
                        .HasColumnType("text");

                    b.Property<Guid>("EweId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LambingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NumberAlive")
                        .HasColumnType("integer");

                    b.Property<int?>("NumberBorn")
                        .HasColumnType("integer");

                    b.Property<Guid>("TupId")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EweId");

                    b.HasIndex("LambingDate");

                    b.HasIndex("TupId");

                    b.HasIndex("UserId");

                    b.ToTable("LambingRecords");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Sheep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("DateOfDeath")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeetHealth")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FlockId")
                        .HasColumnType("uuid");

                    b.Property<string>("LifeStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfTeeth")
                        .HasColumnType("integer");

                    b.Property<string>("Pedigree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SheepType")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlockId");

                    b.HasIndex("UserId");

                    b.ToTable("Sheep");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.TreatmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Complaint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("DateOfTreatment")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dose")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Illness")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("LambingRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Medication")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("SheepId")
                        .HasColumnType("uuid");

                    b.Property<string>("VetAdvice")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LambingRecordId");

                    b.HasIndex("SheepId");

                    b.ToTable("TreatmentRecords", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.WeightHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SheepId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValueKg")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<DateTime>("WeighedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SheepId", "WeighedAtUtc");

                    b.ToTable("WeightHistory", (string)null);
                });

            modelBuilder.Entity("FlockWise.Core.Entities.BirthRecord", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Sheep", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlockWise.Core.Entities.Sheep", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlockWise.Core.Entities.Sheep", "Sheep")
                        .WithOne("BirthRecord")
                        .HasForeignKey("FlockWise.Core.Entities.BirthRecord", "SheepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Father");

                    b.Navigation("Mother");

                    b.Navigation("Sheep");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Field", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.User", "User")
                        .WithMany("Fields")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Flock", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlockWise.Core.Entities.User", "User")
                        .WithMany("Flocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.FlockNote", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Flock", "Flock")
                        .WithMany("Notes")
                        .HasForeignKey("FlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flock");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.LambingNote", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.LambingRecord", "Lambing")
                        .WithMany("Notes")
                        .HasForeignKey("LambingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlockWise.Core.Entities.LambingRecord", null)
                        .WithMany("AssistanceNotes")
                        .HasForeignKey("LambingRecordId");

                    b.Navigation("Lambing");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.LambingRecord", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Sheep", null)
                        .WithMany()
                        .HasForeignKey("EweId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lambing_Sheep_Ewe");

                    b.HasOne("FlockWise.Core.Entities.Sheep", null)
                        .WithMany()
                        .HasForeignKey("TupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lambing_Sheep_Tup");

                    b.HasOne("FlockWise.Core.Entities.User", "User")
                        .WithMany("LambingRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Sheep", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Flock", "Flock")
                        .WithMany("Sheep")
                        .HasForeignKey("FlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlockWise.Core.Entities.User", "User")
                        .WithMany("Sheep")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.TreatmentRecord", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.LambingRecord", null)
                        .WithMany("TreatmentRecords")
                        .HasForeignKey("LambingRecordId");

                    b.HasOne("FlockWise.Core.Entities.Sheep", null)
                        .WithMany()
                        .HasForeignKey("SheepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlockWise.Core.Entities.WeightHistory", b =>
                {
                    b.HasOne("FlockWise.Core.Entities.Sheep", null)
                        .WithMany("Weights")
                        .HasForeignKey("SheepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Flock", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("Sheep");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.LambingRecord", b =>
                {
                    b.Navigation("AssistanceNotes");

                    b.Navigation("Notes");

                    b.Navigation("TreatmentRecords");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.Sheep", b =>
                {
                    b.Navigation("BirthRecord");

                    b.Navigation("Weights");
                });

            modelBuilder.Entity("FlockWise.Core.Entities.User", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Flocks");

                    b.Navigation("LambingRecords");

                    b.Navigation("Sheep");
                });
#pragma warning restore 612, 618
        }
    }
}
